package org.saas.kmp.screens.sampledata

import org.saas.kmp.model.HouseProperty

object SampleData {
    val sampleProperties: List<HouseProperty> by lazy {
        listOf(
            HouseProperty(
                id = "ING001",
                title = "Modern Studio near Audi",
                address = "Audistraße 15, 85057 Ingolstadt",
                price = 650,
                rooms = 1,
                area = 35,
                description = "Bright studio apartment close to Audi headquarters, perfect for young professionals.",
                features = listOf("Furnished", "Balcony", "WiFi", "Near Public Transport"),
                contactEmail = "studio.audi@ingolstadt-rent.de",
                contactPhone = "+49 841 123 4567",
                landlordName = "Thomas Bauer",
                matchPercentage = 92
            ),
            HouseProperty(
                id = "ING002",
                title = "Cozy 2-Room Apartment Altstadt",
                address = "Theresienstraße 8, 85049 Ingolstadt",
                price = 750,
                rooms = 2,
                area = 55,
                description = "Charming apartment in historic old town with traditional Bavarian character.",
                features = listOf("Historic Building", "City Center", "Heating", "Nearby Shopping"),
                contactEmail = "altstadt@wohnen-ingolstadt.de",
                contactPhone = "+49 841 987 6543",
                landlordName = "Maria Huber",
                matchPercentage = 88
            ),
            HouseProperty(
                id = "ING003",
                title = "Student-Friendly Flat",
                address = "Esplanade 23, 85049 Ingolstadt",
                price = 450,
                rooms = 1,
                area = 28,
                description = "Affordable studio perfect for students, near THI campus and city center.",
                features = listOf("Student Housing", "WiFi", "Laundry Room", "Bike Storage"),
                contactEmail = "student@thi-housing.de",
                contactPhone = "+49 841 555 1234",
                landlordName = "Stefan Koch",
                matchPercentage = 95
            ),
            HouseProperty(
                id = "ING004",
                title = "Spacious 2BR near Danube",
                address = "Donaustraße 42, 85051 Ingolstadt",
                price = 850,
                rooms = 2,
                area = 68,
                description = "Beautiful apartment with river views and easy access to green spaces.",
                features = listOf("River View", "Balcony", "Parking", "Near Parks"),
                contactEmail = "danube.view@riverrent.de",
                contactPhone = "+49 841 777 8899",
                landlordName = "Andrea Müller",
                matchPercentage = 85
            ),
            HouseProperty(
                id = "ING005",
                title = "Modern Loft Nordbahnhof",
                address = "Bahnhofstraße 67, 85055 Ingolstadt",
                price = 950,
                rooms = 2,
                area = 75,
                description = "Contemporary loft-style apartment in the trendy Nordbahnhof district.",
                features = listOf("Loft Style", "High Ceilings", "Modern Kitchen", "Near Train Station"),
                contactEmail = "loft@nordbahnhof-living.de",
                contactPhone = "+49 841 333 4455",
                landlordName = "Michael Wagner",
                matchPercentage = 78
            ),
            HouseProperty(
                id = "ING006",
                title = "Affordable 1BR Friedrichshofen",
                address = "Münchener Straße 156, 85053 Ingolstadt",
                price = 550,
                rooms = 1,
                area = 42,
                description = "Budget-friendly apartment in quiet residential area with good bus connections.",
                features = listOf("Quiet Area", "Bus Stop Nearby", "Balcony", "Storage Room"),
                contactEmail = "friedrichshofen@budget-homes.de",
                contactPhone = "+49 841 666 7788",
                landlordName = "Petra Schneider",
                matchPercentage = 90
            ),
            HouseProperty(
                id = "ING007",
                title = "Executive 3BR Piusviertel",
                address = "Goethestraße 34, 85049 Ingolstadt",
                price = 1000,
                rooms = 3,
                area = 85,
                description = "Premium apartment in upscale Piusviertel district, ideal for executives.",
                features = listOf("Premium Location", "Parking", "Balcony", "High-End Appliances"),
                contactEmail = "executive@pius-luxury.de",
                contactPhone = "+49 841 111 2233",
                landlordName = "Dr. Klaus Richter",
                matchPercentage = 72
            ),
            HouseProperty(
                id = "ING008",
                title = "Cozy Studio Südwest",
                address = "Ringseestraße 89, 85057 Ingolstadt",
                price = 480,
                rooms = 1,
                area = 32,
                description = "Small but efficient studio in peaceful Südwest district with park access.",
                features = listOf("Park Nearby", "Quiet", "Furnished", "Pet-Friendly"),
                contactEmail = "southwest@cozy-ingolstadt.de",
                contactPhone = "+49 841 444 5566",
                landlordName = "Julia Fischer",
                matchPercentage = 87
            ),
            HouseProperty(
                id = "ING009",
                title = "Family 2BR Oberhaunstadt",
                address = "Haunstadter Straße 201, 85051 Ingolstadt",
                price = 780,
                rooms = 2,
                area = 62,
                description = "Family-friendly apartment with playground nearby and good school access.",
                features = listOf("Family-Friendly", "Playground", "Schools Nearby", "Garden Access"),
                contactEmail = "family@oberhaunstadt.de",
                contactPhone = "+49 841 888 9900",
                landlordName = "Frank Zimmermann",
                matchPercentage = 83
            ),
            HouseProperty(
                id = "ING010",
                title = "Modern 1BR Mailing",
                address = "Mailinger Straße 78, 85055 Ingolstadt",
                price = 650,
                rooms = 1,
                area = 45,
                description = "Newly renovated apartment with modern amenities in growing Mailing district.",
                features = listOf("Newly Renovated", "Modern Kitchen", "WiFi", "Laundry"),
                contactEmail = "modern@mailing-apts.de",
                contactPhone = "+49 841 222 3344",
                landlordName = "Sandra Weber",
                matchPercentage = 89
            ),
            HouseProperty(
                id = "ING011",
                title = "Budget Studio Ringsee",
                address = "Am Ringsee 145, 85057 Ingolstadt",
                price = 420,
                rooms = 1,
                area = 25,
                description = "Compact and affordable studio near Ringsee lake, perfect for minimalists.",
                features = listOf("Lake Access", "Affordable", "Basic Furnishing", "Nature Nearby"),
                contactEmail = "budget@ringsee-living.de",
                contactPhone = "+49 841 555 6677",
                landlordName = "Martin Braun",
                matchPercentage = 94
            ),
            HouseProperty(
                id = "ING012",
                title = "Charming 2BR Etting",
                address = "Ettinger Straße 92, 85055 Ingolstadt",
                price = 720,
                rooms = 2,
                area = 58,
                description = "Charming apartment in suburban Etting with garden view and parking.",
                features = listOf("Garden View", "Parking Space", "Quiet Location", "Storage"),
                contactEmail = "charming@etting-homes.de",
                contactPhone = "+49 841 777 1122",
                landlordName = "Gabriele Hofmann",
                matchPercentage = 81
            ),
            HouseProperty(
                id = "ING013",
                title = "Central 1BR Zentrum",
                address = "Ludwigstraße 19, 85049 Ingolstadt",
                price = 800,
                rooms = 1,
                area = 48,
                description = "Prime location in city center, walking distance to all major attractions.",
                features = listOf("City Center", "Walking Distance", "Shops Nearby", "Public Transport"),
                contactEmail = "central@zentrum-living.de",
                contactPhone = "+49 841 999 0011",
                landlordName = "Oliver Schmidt",
                matchPercentage = 86
            ),
            HouseProperty(
                id = "ING014",
                title = "Tech Worker Studio",
                address = "Innovationspark 33, 85057 Ingolstadt",
                price = 700,
                rooms = 1,
                area = 40,
                description = "Modern studio designed for tech workers, near innovation park and startups.",
                features = listOf("Tech Hub", "High-Speed Internet", "Desk Space", "Meeting Rooms"),
                contactEmail = "tech@innovation-apts.de",
                contactPhone = "+49 841 123 9876",
                landlordName = "Alexander Tech",
                matchPercentage = 91
            ),
            HouseProperty(
                id = "ING015",
                title = "Affordable 2BR Spitalhof",
                address = "Spitalhofstraße 167, 85049 Ingolstadt",
                price = 600,
                rooms = 2,
                area = 52,
                description = "Good value apartment in established neighborhood with local amenities.",
                features = listOf("Local Shops", "Bus Route", "Balcony", "Basement Storage"),
                contactEmail = "affordable@spitalhof.de",
                contactPhone = "+49 841 456 7890",
                landlordName = "Ingrid Lange",
                matchPercentage = 88
            ),
            HouseProperty(
                id = "ING016",
                title = "Riverside 2BR Donaupark",
                address = "Donaupark 88, 85051 Ingolstadt",
                price = 900,
                rooms = 2,
                area = 70,
                description = "Beautiful apartment overlooking Donaupark with premium river access.",
                features = listOf("Park View", "River Access", "Premium Location", "Bike Paths"),
                contactEmail = "riverside@donaupark-luxury.de",
                contactPhone = "+49 841 333 5577",
                landlordName = "Christina Park",
                matchPercentage = 79
            ),
            HouseProperty(
                id = "ING017",
                title = "Student Share Flat",
                address = "Hollerstauden 234, 85055 Ingolstadt",
                price = 400,
                rooms = 1,
                area = 18,
                description = "Room in shared student apartment, perfect for international students.",
                features = listOf("Shared Kitchen", "Student Community", "WiFi", "Near University"),
                contactEmail = "share@student-community.de",
                contactPhone = "+49 841 666 3344",
                landlordName = "Student Services GmbH",
                matchPercentage = 96
            ),
            HouseProperty(
                id = "ING018",
                title = "Professional 2BR Südost",
                address = "Südoststraße 145, 85057 Ingolstadt",
                price = 825,
                rooms = 2,
                area = 64,
                description = "Professional apartment in developing Südost area, ideal for commuters.",
                features = listOf("Professional Setup", "Parking", "Modern Appliances", "Bus Access"),
                contactEmail = "professional@suedost-living.de",
                contactPhone = "+49 841 789 0123",
                landlordName = "Markus Professional",
                matchPercentage = 84
            ),
            HouseProperty(
                id = "ING019",
                title = "Compact 1BR Niederfeld",
                address = "Niederfelder Weg 77, 85053 Ingolstadt",
                price = 580,
                rooms = 1,
                area = 38,
                description = "Compact yet comfortable apartment in residential Niederfeld district.",
                features = listOf("Residential Area", "Quiet", "Basic Amenities", "Affordable"),
                contactEmail = "compact@niederfeld-apts.de",
                contactPhone = "+49 841 555 8899",
                landlordName = "Helga Niederfeld",
                matchPercentage = 85
            ),
            HouseProperty(
                id = "ING020",
                title = "Modern 2BR Kothau",
                address = "Kothauer Straße 198, 85055 Ingolstadt",
                price = 750,
                rooms = 2,
                area = 60,
                description = "Modern apartment in up-and-coming Kothau district with excellent transport links.",
                features = listOf("Modern Design", "Transport Links", "Shopping Center", "Community"),
                contactEmail = "modern@kothau-new.de",
                contactPhone = "+49 841 111 4455",
                landlordName = "Neue Wohnen GmbH",
                matchPercentage = 82
            )
        )
    }
}
